import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Ethos",
    description: "Operating Principles v2.0.4. Against perfection. Digital decay. Visceral utility.",
    openGraph: {
        title: "Ethos | MONK HAUS",
        description: "The internet was born as a library. It turned into a shopping mall. We are returning it to the library.",
        url: "https://monk.haus/ethos",
    },
};

export default function EthosPage() {
    return (
        <main className="relative w-full bg-void min-h-screen cursor-crosshair overflow-x-hidden selection:bg-signal selection:text-void">
            <section className="relative min-h-[90vh] w-full flex flex-col justify-between p-4 md:p-6 border-b border-newsprint/10">
                <div className="absolute top-20 right-4 md:top-24 md:right-6 z-0 text-right">
                    <div className="font-mono text-[10px] md:text-xs leading-tight text-newsprint/60 uppercase tracking-widest space-y-4">
                        <p>
                            Document:<br />
                            <span className="text-newsprint">Manifesto</span>
                        </p>
                        <p>
                            Date:<br />
                            <span className="text-newsprint">2026</span>
                        </p>
                    </div>
                </div>

                <div className="mt-auto z-10 pt-32 pb-12 md:pb-0">
                    <h1 className="font-alpina text-newsprint leading-[0.85] mix-blend-difference">
                        <span className="block text-[14vw] md:text-[12vw] tracking-[-0.03em] lowercase">
                            against
                        </span>
                        <span className="block text-[14vw] md:text-[12vw] tracking-[-0.03em] lowercase ml-[8vw]">
                            <span className="italic text-newsprint/50">perfection</span>
                        </span>
                    </h1>
                </div>
            </section>

            <section className="relative w-full py-24 px-4 md:px-6 border-b border-newsprint/10">
                <div className="max-w-screen-xl mx-auto grid grid-cols-1 md:grid-cols-12 gap-12">
                    <div className="md:col-span-4 sticky top-32 h-fit">
                        <span className="font-mono text-xs text-signal uppercase tracking-widest block mb-4">
                            01 / The Crisis
                        </span>
                        <p className="font-mono text-xs text-newsprint/60 leading-relaxed max-w-[240px]">
                            The internet was born as a library. It turned into a shopping mall. We are returning it to the library.
                        </p>
                    </div>

                    <div className="md:col-span-8">
                        <h2 className="font-alpina text-3xl md:text-5xl text-newsprint leading-[1.1] mb-12">
                            We are drowning in "Clean." <br />
                            Clean is safe. Clean is scalable. <br />
                            <span className="text-newsprint/50 italic">Clean is dead.</span>
                        </h2>

                        <div className="prose font-mono text-sm text-newsprint/80 leading-loose space-y-8 max-w-2xl">
                            <p>
                                Every SaaS website looks the same. The same gradients. The same rounded corners. The same illustration of a happy team high-fiving. It is a visual language designed to numb you, to slide you frictionless down a funnel until you click "Subscribe."
                            </p>
                            <p>
                                Monk exists to reintroduce friction. We believe that if you don't feel the texture of a digital space, you aren't really inhabiting it. We build interfaces that demand attention, that have weight, that feel like they were made by human hands, not generated by a template.
                            </p>
                            <p>
                                We don't want you to "browse" our work. We want you to collide with it.
                            </p>
                        </div>
                    </div>
                </div>
            </section>

            <section className="relative w-full bg-newsprint text-void py-32 px-4 md:px-6">
                <div className="max-w-screen-xl mx-auto">
                    <div className="mb-24">
                        <h2 className="font-alpina text-6xl md:text-9xl tracking-tight leading-none mb-4">
                            The <span className="italic text-void/40">Code</span>
                        </h2>
                        <div className="w-full h-[1px] bg-void/20 mt-8"></div>
                    </div>

                    <div className="grid grid-cols-1 gap-16">
                        <div className="grid grid-cols-1 md:grid-cols-12 gap-8 items-start group">
                            <div className="md:col-span-2 font-mono text-xs text-signal uppercase tracking-widest pt-2">
                                01 / Craft
                            </div>
                            <div className="md:col-span-10 border-t border-void/10 pt-2">
                                <h3 className="font-alpina text-4xl md:text-6xl mb-6 group-hover:italic transition-all">
                                    No Templates. Ever.
                                </h3>
                                <p className="font-mono text-sm text-void/60 max-w-xl leading-relaxed">
                                    Templates are the fast food of the internet. We cook from scratch. Every line of code is written for the specific problem at hand. If we have done it before, we don't do it again.
                                </p>
                            </div>
                        </div>

                        <div className="grid grid-cols-1 md:grid-cols-12 gap-8 items-start group">
                            <div className="md:col-span-2 font-mono text-xs text-signal uppercase tracking-widest pt-2">
                                02 / Imperfection
                            </div>
                            <div className="md:col-span-10 border-t border-void/10 pt-2">
                                <h3 className="font-alpina text-4xl md:text-6xl mb-6 group-hover:italic transition-all">
                                    Digital Decay.
                                </h3>
                                <p className="font-mono text-sm text-void/60 max-w-xl leading-relaxed">
                                    Nothing digital is permanent, but we pretend it is. We embrace the glitch, the grain, the artifact. We design systems that look better when they break.
                                </p>
                            </div>
                        </div>

                        <div className="grid grid-cols-1 md:grid-cols-12 gap-8 items-start group">
                            <div className="md:col-span-2 font-mono text-xs text-signal uppercase tracking-widest pt-2">
                                03 / Impact
                            </div>
                            <div className="md:col-span-10 border-t border-void/10 pt-2">
                                <h3 className="font-alpina text-4xl md:text-6xl mb-6 group-hover:italic transition-all">
                                    Visceral Utility.
                                </h3>
                                <p className="font-mono text-sm text-void/60 max-w-xl leading-relaxed">
                                    A website must work, but "working" isn't enough. A hammer works. A scalpel works. We build tools that feel dangerous in your hand. High utility, high impact.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <section className="relative w-full bg-void text-newsprint py-32 px-4 md:px-6">
                <div className="max-w-screen-xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-16 md:gap-32 items-center">
                    <div className="relative w-full aspect-square md:aspect-auto md:h-[400px] border border-newsprint/20 p-8 flex flex-col justify-between hover:bg-newsprint/5 transition-colors duration-500">
                        <div className="space-y-6">
                            <span className="font-mono text-xs text-signal uppercase tracking-widest block">
                                The Process
                            </span>
                            <h3 className="font-alpina text-3xl md:text-4xl leading-tight">
                                From Chaos to <span className="italic text-newsprint/50">Clarity</span>.
                            </h3>
                        </div>

                        <div className="space-y-4 font-mono text-xs text-newsprint/60 leading-relaxed uppercase tracking-widest">
                            <div className="flex justify-between items-center border-b border-newsprint/10 pb-2">
                                <span>Input</span>
                                <span className="text-newsprint">Raw Concept</span>
                            </div>
                            <div className="flex justify-between items-center border-b border-newsprint/10 pb-2">
                                <span>Method</span>
                                <span className="text-newsprint">Reduction</span>
                            </div>
                            <div className="flex justify-between items-center pt-2">
                                <span>Result</span>
                                <span className="text-newsprint">Essential Form</span>
                            </div>
                        </div>
                    </div>

                    <div className="flex flex-col justify-center h-full">
                        <h2 className="font-alpina text-4xl md:text-5xl mb-8">
                            The Studio
                        </h2>
                        <p className="font-mono text-sm text-newsprint/70 leading-loose mb-8">
                            We are a studio, not a factory. We operate as a small team of obsessives. We limit our intake to ensure total immersion in every project.
                        </p>
                        <p className="font-mono text-sm text-newsprint/70 leading-loose">
                            When you work with Monk, you don't get an account manager. You don't get a sales rep. You get the hands doing the work. The line is direct. The feedback is raw. The output is personal.
                        </p>
                    </div>
                </div>
            </section>

            <footer className="relative w-full bg-void pt-24 pb-8 px-4 md:px-6 border-t border-newsprint/10">
                <div className="border-b border-newsprint/10 pb-24">
                    <a href="mailto:hello@monk.haus" className="group block">
                        <span className="font-mono text-xs text-newsprint/40 mb-4 block ml-2 uppercase tracking-widest">
                            Inquiries
                        </span>
                        <h2 className="font-alpina text-[12vw] leading-[0.8] text-newsprint group-hover:text-signal transition-colors duration-0">
                            hello@monk.haus
                        </h2>
                    </a>
                </div>

                <div className="pt-8 flex flex-col md:flex-row justify-between items-start md:items-end gap-8 font-mono text-[10px] uppercase tracking-widest text-newsprint/60">
                    <div className="flex flex-col gap-2">
                        <span className="text-newsprint">Location</span>
                        <span>
                            Craiova, RO <br />
                            {new Date().toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', timeZoneName: 'short' })}
                        </span>
                    </div>

                    <div className="flex gap-8">
                        <a
                            href="https://instagram.com/_monk.haus_"
                            target="_blank"
                            rel="noopener noreferrer"
                            className="hover:text-newsprint transition-colors"
                        >
                            Instagram
                        </a>
                    </div>

                    <div className="text-right">
                        <span>Monk Haus © 2026</span> <br />
                        <span className="text-newsprint/40">All Rights Reserved.</span>
                    </div>
                </div>
            </footer>
        </main>
    );
}